server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  metrics: 
    enabled: true
  health:
    sensitive: false
    
multipart:
  max-file-size: 999999999
  max-request-size: 999999999
  maxFileSize: 999999999
  maxRequestSize: 999999999     

spring:
  main:
    show_banner: false
    banner-mode: "off"
  application:
    name: thymeleaf
  datasource: 
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:data/derby/exampleCrud;create=true;user=system;password=agf@392
    username: system
    password: agf@392
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.DerbyTenSevenDialect
